[package]
name = "klone"
version = "0.0.0"
edition = "2021"
description = "Reserved"
authors = "[kinire98]"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
